language: cpp

env:
  global:
    - CTEST_EXT_COLOR_OUTPUT=TRUE

compiler:
  - clang
  - gcc
dist: trusty

before_script:  
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make -j
  - ctest --timeout 300 --output-on-failure